- !Battle
  id: 1302
  start_time: 0:00:01
  end_time: 0:01:07
- !Battle
  id: 1302
  start_time: 0:01:14
  end_time: 0:01:36
- !Battle
  id: 1302
  start_time: 0:01:44
  end_time: 0:02:06
- !Battle
  id: 1302
  start_time: 0:02:14
  end_time: 0:02:32
- !Battle
  id: 1302
  start_time: 0:02:38
  end_time: 0:03:01
- !Battle
  id: 1302
  start_time: 0:03:09
  end_time: 0:03:36
- !Battle
  id: 1302
  start_time: 0:03:42
  end_time: 0:04:03
- !Battle
  id: 1302
  start_time: 0:04:08
  end_time: 0:04:29